---
title: "Postestimation: Testing a model"
subtitle: "Using the `test_*()` family of functions"
date: "Last edited: `r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: true
vignette: >
  %\VignetteIndexEntry{using-test}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: ../inst/REFERENCES.bib
---
WARNING: this document is work in progress.

# Introduction {#introduction}

An introduction.

# Syntax & Options {#syntax}

```{r eval=FALSE}
testOMF(
  .object                = args_default()$.object, 
  .alpha                 = args_default()$.alpha, 
  .handle_inadmissibles  = args_default()$.handle_inadmissibles, 
  .R                     = args_default()$.R, 
  .saturated             = args_default()$.saturated,
  .seed                  = args_default()$.seed,
  .verbose               = args_default()$.verbose
  )

testMGD(
  .object                = args_default()$.object,
  .alpha                 = args_default()$.alpha,
  .approach_p_adjust     = args_default()$.approach_p_adjust,
  .approach_mgd          = args_default()$.approach_mgd,
  .model                 = args_default()$.model,
  .handle_inadmissibles  = args_default()$.handle_inadmissibles,
  .R_permutation         = args_default()$.R_permutation,
  .R_bootstrap           = args_default()$.R_bootstrap,
  .saturated             = args_default()$.saturated,
  .seed                  = args_default()$.seed,
  .type_vcv              = args_default()$.type_vcv,
  .verbose               = args_default()$.verbose
  ) 

testHausman2(
 .object               = NULL,
 .alpha                = args_default()$.alpha,
 .eval_plan            = args_default()$.eval_plan,
 .handle_inadmissibles = args_default()$.handle_inadmissibles,
 .R                    = args_default()$.R,
 .resample_method      = args_default()$.resample_method,
 .seed                 = args_default()$.seed
)

testMICOM(
  .object               = args_default()$.object,
  .alpha                = args_default()$.alpha,
  .approach_p_adjust    = args_default()$.approach_p_adjust, 
  .handle_inadmissibles = args_default()$.handle_inadmissibles,
  .R                    = args_default()$.R,
  .seed                 = args_default()$.seed,
  .verbose              = args_default()$.verbose
  )
```

`.object`

:   An object of class `cSEMResults` resulting from a call to `csem()`.
   
`.alpha`

:  	An integer or a numeric vector of significance levels. Defaults to `0.05`.
  

`.eval_plan`

:   Character string. The evaluation plan to use. One of "sequential" or 
    "multiprocess". In the latter case all available cores will be used. 
Defaults to "sequential". See `resamplecSEMResults()` for details.
   
`.handle_inadmissibles`

:   Character string. How should inadmissible results be treated during 
    bootstrap/permutation? One of "drop", "ignore", or "replace". 
    If "drop", inadmissibles estimations are dropped (i.e., the number of 
    results returned will be likely less than .R). For "ignore" inadmissible estimations are 
    returned even if they are inadmissible (i.e., number of results
    returned = .R). For "replace" inadmissible estimations are replaced, i.e.,
    resampling continues until there are exactly .R admissible solutions 
    (i.e., number of results returned equal .R). Defaults to "drop".

`.R`

:   Integer. The number of bootstrap/permutation runs. Defaults to `499`.

`.resample_method`

:   Character string. The resampling method to use. One of: "bootstrap" or "jackknife". 
    Defaults to "bootstrap".

`.saturated`

:   Logical. Whether the model-implied indicator variance-covariance matrix 
    should be based on the a saturated structural model. Defaults to `FALSE` 

`.seed`

:   Integer or `NULL`. The random seed to use. Defaults to `NULL` in which case
    an arbitrary seed is choosen.

`.type_vcv`

:   Character string. Indicates which model-implied correlation matrix is compared
    across groups. One of "*indicator*" or "*construct*". Defaults to "*indicator*".
    
`.verbose`

:   
## Details

Details if there are any.

# Usage & Examples {#examples}

## Example 1 {#example1}
## Example 2 {#example2}
## Example 3 {#example3}

# Methods & Formulae {#methods}

## Test for overall model fit {#topic1}
### Definition

### Formula

### Implementation

### See also

## Test for multigroup differences {#topic2}
### Definition

### Formula

### Implementation

### See also

## Hausman test for endogeneity {#topic3}
### Definition

### Formula

### Implementation

### See also

## Test for composite measurement invariance {#topic4}
### Definition

### Formula

### Implementation

### See also

# Literature
