# Context by David Maze https://stackoverflow.com/a/65596096
# RStudio Config by asachet https://stackoverflow.com/a/54982341
# ${HOME} by Lesnek https://stackoverflow.com/a/62408283
services:
  rstudioweb:
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
    image: csem
    environment:
      - PASSWORD=password
    ports:
      - "8787:8787"
    volumes:
      - ..:/home/rstudio/project
      - ${HOME}/.config/rstudio/rstudio-prefs.json:/home/rstudio/.config/rstudio/rstudio-prefs.json