// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// arma_svd_X
arma::vec arma_svd_X(const arma::mat& X, const arma::vec& y);
RcppExport SEXP _cSEM_arma_svd_X(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(arma_svd_X(X, y));
    return rcpp_result_gen;
END_RCPP
}
// arma_svd_XtX
arma::vec arma_svd_XtX(const arma::mat& X, const arma::vec& y);
RcppExport SEXP _cSEM_arma_svd_XtX(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(arma_svd_XtX(X, y));
    return rcpp_result_gen;
END_RCPP
}
// arma_pinv
arma::vec arma_pinv(const arma::mat& X, const arma::vec& y);
RcppExport SEXP _cSEM_arma_pinv(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(arma_pinv(X, y));
    return rcpp_result_gen;
END_RCPP
}
// arma_solve
arma::vec arma_solve(const arma::mat& X, const arma::vec& y);
RcppExport SEXP _cSEM_arma_solve(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(arma_solve(X, y));
    return rcpp_result_gen;
END_RCPP
}
// arma_update_U_qrQ
arma::mat arma_update_U_qrQ(const arma::mat& Eta_normed, const arma::mat& Z_normed, const arma::mat& D);
RcppExport SEXP _cSEM_arma_update_U_qrQ(SEXP Eta_normedSEXP, SEXP Z_normedSEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Eta_normed(Eta_normedSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_normed(Z_normedSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_update_U_qrQ(Eta_normed, Z_normed, D));
    return rcpp_result_gen;
END_RCPP
}
// arma_update_U_qrqty
arma::mat arma_update_U_qrqty(const arma::mat& Eta_normed, const arma::mat& Z_normed, const arma::mat& D);
RcppExport SEXP _cSEM_arma_update_U_qrqty(SEXP Eta_normedSEXP, SEXP Z_normedSEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Eta_normed(Eta_normedSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z_normed(Z_normedSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_update_U_qrqty(Eta_normed, Z_normed, D));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cSEM_arma_svd_X", (DL_FUNC) &_cSEM_arma_svd_X, 2},
    {"_cSEM_arma_svd_XtX", (DL_FUNC) &_cSEM_arma_svd_XtX, 2},
    {"_cSEM_arma_pinv", (DL_FUNC) &_cSEM_arma_pinv, 2},
    {"_cSEM_arma_solve", (DL_FUNC) &_cSEM_arma_solve, 2},
    {"_cSEM_arma_update_U_qrQ", (DL_FUNC) &_cSEM_arma_update_U_qrQ, 3},
    {"_cSEM_arma_update_U_qrqty", (DL_FUNC) &_cSEM_arma_update_U_qrqty, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_cSEM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
