<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>GSCA and GSCA<sub>M</sub> • cSEM</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/all.min.css" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/v4-shims.min.css" integrity="sha256-6qHlizsOWFskGlwVOKuns+D1nB6ssZrHQrNj1wGplHc=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="GSCA and GSCA&lt;sub&gt;M&lt;/sub&gt;">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">cSEM</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.0.0.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/cSEM.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/GSCA.html">GSCA and GSCA&lt;sub&gt;M&lt;/sub&gt;</a>
    </li>
    <li>
      <a href="../articles/PLS.html">PLS-PM</a>
    </li>
    <li>
      <a href="../articles/Using-assess.html">Postestimation: Assessing a model</a>
    </li>
    <li>
      <a href="../articles/Using-summarize.html">Postestimation: Summarizing results</a>
    </li>
    <li>
      <a href="../articles/Using-test.html">Postestimation: Testing a model</a>
    </li>
    <li>
      <a href="../articles/Using-verify.html">Postestimation: Verifying results</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/M-E-Rademaker/cSEM">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>GSCA and GSCA<sub>M</sub>
</h1>
            <h3 class="subtitle">Generalized structured component analysis with and without uniquness terms</h3>
            
            <h4 class="date">2019-04-24</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/M-E-Rademaker/cSEM/blob/master/vignettes/GSCA.Rmd"><code>vignettes/GSCA.Rmd</code></a></small>
      <div class="hidden name"><code>GSCA.Rmd</code></div>

    </div>

    
    
<p>WARNING: this document is work in progress.</p>
<div id="introduction" class="section level1">
<h1 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h1>
<!-- This helpfile provides additional information about the GSCA approach for structural equation models and its implementation in the *cSEM*-package. The aim of the following document is to explain to the user, how to proceed when parameters of a structural model shall be estimated with GSCA or GSCA<sub>M</sub>. The usage of GSCA and GSCA<sub>M</sub> as well as the general structure of the output are explained via an estimation example which will also provide an idea of how estimation results can be interpreted.  -->
<!-- The implemented routine calculates weights, as well as path coefficients and  -->
<!-- loadings of a structural equation model with the GSCA procedure.  -->
<p>Generalized structured component analysis (GSCA) and generalized structured componenent analysis with uniquness terms (GSCA<sub>M</sub>) is a composite-based approach to structural equation modeling introduced and refined by <span class="citation">Hwang and Takane (2004)</span>; <span class="citation">Hwang and Takane (2014)</span> and <span class="citation">Hwang, Takane, and Jung (2017)</span>.</p>
<!-- It is in several points comparable to PLS.  -->
<p>As in other composite-based approaches such as partial least squares (PLS) or prinicpal component analysis (PCA), GSCA and GSCA<sub>M</sub> use composites, i.e., as exact linear combinations of related observables (indicators). The corresponding composite weights are estimated by minimizing a global optimization criterion via linear regressions involving latent variables (resp. their proxies) and the observed indicators (see <span class="citation">(Hwang and Takane 2014, 8–10)</span>).</p>
<p>Both GSCA and GSCA<sub>M</sub> do not make any assumption concerning the distribution of the structural and/or measurement errors. <!-- That is why, --> <!-- estimators finally have to be calculated via Least Squares. --> Basic to GSCA and GSCA<sub>M</sub> is that three submodels are combined to build up the overall GSCA/GSCA<sub>M</sub>-model. These are the structural model (relationships among constructs), measurement model (influence of constructs on indicators expressed by loadings) and weighted relation model (constructs as linear combinations of indicators) (for a detailed description see <span class="citation">(Hwang and Takane 2014, chaps. 2.1–2.2)</span>). The <a href="#methods">Methods &amp; Formula</a> provides more details.</p>
<p>As described in detail in the <a href="https://m-e-rademaker.github.io/cSEM/articles/cSEM.html">Introduction to cSEM</a> parameter estimates obtained using GSCA are biased if concepts are modeled as common factors. <!-- It is possible that the estimated parameters, especially loadings, are biased  --> <!-- when using GSCA. In particular, this is the case when indicators are observed  --> <!-- with an error. --> However, GSCA<sub>M</sub> offers a way to estimate the parameters also in this situation consistently. The term “GSCA<sub>M</sub>” stands for “GSCA with measurement errors incorporated”. This approach was presented in <span class="citation">(Hwang, Takane, and Jung 2017)</span>. The main idea of GSCA<sub>M</sub> is to model indicators in the measurement model as a combination of common parts (arising from the constructs) and unique parts. The purpose of adding a unique part to each indicator is to account for measurement errors in the indicators. In a next step, latent variables are expressed in the weighted relation model as a linear combination of indicators but with their unique parts removed (see <span class="citation">(Hwang, Takane, and Jung 2017, 1–3)</span>). For some formula and details see Section <a href="#methods">Methods</a>. For the estimation with GSCA and GSCA<sub>M</sub> using the functions of the cSEM-package see Sections <a href="#usage">Implementation</a> and <a href="#examples">Examples</a>.</p>
</div>
<div id="usage" class="section level1">
<h1 class="hasAnchor">
<a href="#usage" class="anchor"></a>Syntax and Options</h1>
<p>Suppose that a structural model ‘model’ is specified in Lavaan-syntax and that data are given in form of an observation matrix ‘data’. To estimate parameters now in this specified structural model by means of GSCA (or GSCA<sub>M</sub>) for the given data, the user has to call the function <em>csem()</em>:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw"><a href="../reference/csem.html">csem</a></span>(<span class="dt">.data =</span> data, <span class="dt">.model =</span> model, <span class="dt">.approach_weights =</span> <span class="st">"GSCA"</span>, <span class="dt">.disattenuate =</span> )</a></code></pre></div>
<p>Although the <em>csem</em>-function has many more input arguments, it suffices in the case of GSCA in a first step to specify the input arguments <em>‘.model’</em> and <em>‘.data’</em> and to set the argument <em>‘.approach_weights’</em> equal to <em>“GSCA”</em>. The argument <em>‘.disattenuate’</em> indicates which of the two GSCA-approaches should be used. Its default value is <em>TRUE</em> resulting in GSCA<sub>M</sub> as estimation method whereas a value of <em>FALSE</em> leads to “standard” GSCA. The handling of the <em>‘.disattenuate’</em>-argument is explained more detailly in the following paragraphs and in the Section <a href="#examples">Examples</a>. By this, the user gets a concrete idea in which cases this argument has to be specified and in which it can be dropped.</p>
<p>With “GSCA” as chosen approach, estimation is automatically done via GSCA<sub>M</sub> when calling the <em>csem</em>-function. This works out fine as long as all constructs are of common factor type (i.e. the construct has an influence on its indicators and vice versa). In this case, GSCA<sub>M</sub> can be applied and the argument <em>‘.disattenuate’</em> can be dropped. Although estimators will be biased, the user might want to estimate parameters in this special case with “standard” GSCA. To this end, the input argument <em>‘.disattenuate’</em> has to be set to <em>FALSE</em>.</p>
<p>However, if there is at least one construct which is not a common factor, parameters cannot be estimated by means of GSCA<sub>M</sub>, but only with “standard” GSCA. The reason is, e.g. in the case of all constructs being pure composites, that the transposed measurement matrix has only zero entries in this situation. Thus, involving this matrix in the estimation procedure, GSCA<sub>M</sub> would lead to weight estimators equal to 0. In the same way, in the case of a mixed model, that is to say when some constructs are of common factor type and some are pure composites, estimation with GSCA<sub>M</sub> causes problems because the measurement matrix cannot not have full rank. Thus, the GSCA<sub>M</sub> approach developed by Hwang and Takane in <span class="citation">(Hwang, Takane, and Jung 2017)</span> does not work for such models. The implementation is based on the current state of research but does not pursue own research goals. That is to say, developping a GSCA<sub>M</sub> procedure for the models with at least one composite type construct is not the aim and, therefore, in these situations, the user imperatively has to use GSCA and GSCA<sub>M</sub> is no option. This necessitates an input argument of <em>‘.disattenuate’</em> equal to <em>FALSE</em>.</p>
<p>Setting the argument <em>‘.disattenuate’</em> equal to <em>TRUE</em> always leads to GSCA<sub>M</sub> as estimation method. Furthermore, dropping the argument also leads to GSCA<sub>M</sub> since its default value is <em>TRUE</em>. In these situations, estimation with GSCA<sub>M</sub> fails in case of a model where at least one construct is not a common factor. Then, the user gets an error message (see also Section <a href="#examples">Examples</a>):</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1">Error<span class="op">:</span><span class="st"> </span>The following error occured <span class="cf">in</span> the <span class="st">`</span><span class="dt">calculateWeightsGSCAm()</span><span class="st">`</span> <span class="cf">function</span><span class="op">:</span></a>
<a class="sourceLine" id="cb2-2" data-line-number="2">GSCAm only applicable to pure common factor models. Use <span class="st">`</span><span class="dt">.disattenuate = FALSE</span><span class="st">`</span>. </a></code></pre></div>
<p>There are two other input-arguments which are of interest when estimating parameters with GSCA or GSCA<sub>M</sub>: <em>‘.iter_max’</em> and <em>‘.tolerance’</em>. Both will be explained in the section <a href="#methods">Methods</a>.</p>
</div>
<div id="examples" class="section level1">
<h1 class="hasAnchor">
<a href="#examples" class="anchor"></a>Usage &amp; Examples</h1>
<div id="example1" class="section level3">
<h3 class="hasAnchor">
<a href="#example1" class="anchor"></a>Example 1: Pure common factor model and GSCA<sub>M</sub>
</h3>
<p>In the following, a first application example of the <em>csem</em>-function for the estimation with GSCA is presented. Data are given in form of the dataset “satisfaction” that comes with the <em>cSEM</em>-package. This dataset consists of 250 observations for 27 indicators. These indicators are somehow related to 6 constructs. Before estimation can be done, a model has to be specified for the relationships among these variables. This model is a result of the user’s ideas, hypotheses and theories about the original subject, which is customer satisfaction in the example. The model specification has to be done in lavaan-syntax. In the structural model, the tilde “~” is the known regression operator. However, in the measurement model, the symbol “&lt;~” is used for pure composites whereas the symbol “=~” stands for common factors. Note that the following specification is just one possible way and does not reflect any common theory about customer satisfaction but is used for illustration purposes only.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(cSEM)</a>
<a class="sourceLine" id="cb3-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(satisfaction)</a>
<a class="sourceLine" id="cb3-3" data-line-number="3"></a>
<a class="sourceLine" id="cb3-4" data-line-number="4">model &lt;-<span class="st"> "</span></a>
<a class="sourceLine" id="cb3-5" data-line-number="5"><span class="st"># Structural model</span></a>
<a class="sourceLine" id="cb3-6" data-line-number="6"><span class="st">QUAL ~ EXPE</span></a>
<a class="sourceLine" id="cb3-7" data-line-number="7"><span class="st">EXPE ~ IMAG</span></a>
<a class="sourceLine" id="cb3-8" data-line-number="8"><span class="st">SAT  ~ IMAG + EXPE + QUAL + VAL</span></a>
<a class="sourceLine" id="cb3-9" data-line-number="9"><span class="st">LOY  ~ IMAG + SAT</span></a>
<a class="sourceLine" id="cb3-10" data-line-number="10"><span class="st">VAL  ~ EXPE + QUAL</span></a>
<a class="sourceLine" id="cb3-11" data-line-number="11"></a>
<a class="sourceLine" id="cb3-12" data-line-number="12"><span class="st"># Measurement model (pure common factor)</span></a>
<a class="sourceLine" id="cb3-13" data-line-number="13"></a>
<a class="sourceLine" id="cb3-14" data-line-number="14"><span class="st">EXPE =~ expe1 + expe2 + expe3 + expe4 + expe5</span></a>
<a class="sourceLine" id="cb3-15" data-line-number="15"><span class="st">IMAG =~ imag1 + imag2 + imag3 + imag4 + imag5</span></a>
<a class="sourceLine" id="cb3-16" data-line-number="16"><span class="st">LOY  =~ loy1  + loy2  + loy3  + loy4</span></a>
<a class="sourceLine" id="cb3-17" data-line-number="17"><span class="st">QUAL =~ qual1 + qual2 + qual3 + qual4 + qual5</span></a>
<a class="sourceLine" id="cb3-18" data-line-number="18"><span class="st">SAT  =~ sat1  + sat2  + sat3  + sat4</span></a>
<a class="sourceLine" id="cb3-19" data-line-number="19"><span class="st">VAL  =~ val1  + val2  + val3  + val4</span></a>
<a class="sourceLine" id="cb3-20" data-line-number="20"><span class="st">"</span></a></code></pre></div>
<p>Having specified the model to be estimated and the data, the user can now call the <em>csem</em>-function:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1">results1 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/csem.html">csem</a></span>(satisfaction, model, <span class="dt">.approach_weights =</span> <span class="st">"GSCA"</span>, <span class="dt">.disattenuate =</span> <span class="st">"TRUE"</span>)</a></code></pre></div>
<p>Note that in this case, the user could also drop the input argument <em>‘.disattenuate’</em> because estimation is here done with GSCA<sub>M</sub> as it should. Since it is a pure common factor model, no error message is produced. The estimation results are stored in the object <em>“results1”</em>:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1">results1</a></code></pre></div>
<pre><code>## ______________________________________________________________________________________________________________
## -------------------------------------------------- Overview --------------------------------------------------
## 
## Estimation was successful.
## 
## The result is a list of class cSEMResults with list elements:
## 
##  - Estimates
##  - Information
## 
## To get an overview or help type:
## 
##  - ?cSEMResults
##  - str(&lt;object-name&gt;)
##  - listviewer::jsondedit(&lt;object-name&gt;, mode = 'view')
## 
## If you wish to access the list elements directly type e.g. 
## 
##  - &lt;object-name&gt;$Estimates
## 
## Available postestimation commands:
## 
##  - assess(&lt;object-name&gt;)
##  - summarize(&lt;object-name&gt;)
##  - verify(&lt;object-name&gt;)
## ______________________________________________________________________________________________________________</code></pre>
<p>As indicated, the object <em>“results1”</em> is a list of class <em>cSEMResults</em> with the list elements <em>Estimates</em> and <em>Information</em>. Each sublist contains several elements which can be accessed separately:</p>
<ol style="list-style-type: decimal">
<li>Estimates</li>
</ol>
<ul>
<li>Path_estimates</li>
<li>Loading_estimates</li>
<li>Weight_estimates</li>
<li>Inner_weight_estimates</li>
<li>Construct_scores</li>
<li>Indicator_VCV</li>
<li>Proxy_VCV</li>
<li>Construct_VCV</li>
<li>Construct_reliabilities</li>
<li>R2</li>
<li>R2adj</li>
<li>VIF</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>Information</li>
</ol>
<ul>
<li>Data</li>
<li>Model</li>
<li>Arguments</li>
<li>Type_of_indicator_correlation</li>
<li>Weight_info</li>
</ul>
<p>Depending on the research interests that the user has, the relevant information and estimators can be extracted by the user.</p>
<p>For GSCA, as well as for PLS and the other approaches, some postestimation functions are available: 1. <em>‘assess’</em> 2. <em>‘summarize’</em> 3. <em>‘verify’</em></p>
<p>Firstly, the <em>‘assess’</em>-function provides the user with common evaluation criteria and fit measures to assess the model:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="kw"><a href="../reference/assess.html">assess</a></span>(results1)</a></code></pre></div>
<p>Next, if the user just wants a compact summary of the parameter estimators and of the most important information concerning the estimation, calling the <em>‘summarize’</em>-function of the <em>cSEM</em>-package will provide this.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1"><span class="kw"><a href="../reference/summarize.html">summarize</a></span>(results1)</a></code></pre></div>
<pre><code>## ______________________________________________________________________________________________________________
## -------------------------------------------------- Overview --------------------------------------------------
## 
##  Number of observations           = 250
##  Weight estimator                 = GSCA
##  Type of indicator correlation    = Bravais-Pearson
##  Path model estimator             = OLS
##  Type of path model               = Linear
##  Disattenuated                    = Yes
## 
##  Construct details:
##  ------------------
##  Name  Modeled as     Order         
## 
##  IMAG  Common factor  First order   
##  EXPE  Common factor  First order   
##  QUAL  Common factor  First order   
##  VAL   Common factor  First order   
##  SAT   Common factor  First order   
##  LOY   Common factor  First order   
## 
## -------------------------------------------------- Estimates -------------------------------------------------
## 
## Estimated path coefficients:
## ============================
##   Path           Estimate  Std. error   t-stat.   p-value
##   EXPE ~ IMAG      0.6087          NA        NA        NA
##   QUAL ~ EXPE      0.9397          NA        NA        NA
##   VAL ~ EXPE      -0.2146          NA        NA        NA
##   VAL ~ QUAL       1.0365          NA        NA        NA
##   SAT ~ IMAG       0.0869          NA        NA        NA
##   SAT ~ EXPE      -0.0253          NA        NA        NA
##   SAT ~ QUAL       0.0379          NA        NA        NA
##   SAT ~ VAL        0.8274          NA        NA        NA
##   LOY ~ IMAG       0.3120          NA        NA        NA
##   LOY ~ SAT        0.5098          NA        NA        NA
## 
## Estimated Loadings:
## ===================
##   Loading          Estimate  Std. error   t-stat.   p-value
##   IMAG =~ imag1      0.7098          NA        NA        NA
##   IMAG =~ imag2      0.9126          NA        NA        NA
##   IMAG =~ imag3      0.8375          NA        NA        NA
##   IMAG =~ imag4      0.5587          NA        NA        NA
##   IMAG =~ imag5      0.5597          NA        NA        NA
##   EXPE =~ expe1      0.7598          NA        NA        NA
##   EXPE =~ expe2      0.7736          NA        NA        NA
##   EXPE =~ expe3      0.6656          NA        NA        NA
##   EXPE =~ expe4      0.7000          NA        NA        NA
##   EXPE =~ expe5      0.7699          NA        NA        NA
##   QUAL =~ qual1      0.7414          NA        NA        NA
##   QUAL =~ qual2      0.8322          NA        NA        NA
##   QUAL =~ qual3      0.6879          NA        NA        NA
##   QUAL =~ qual4      0.8625          NA        NA        NA
##   QUAL =~ qual5      0.7625          NA        NA        NA
##   VAL =~ val1        0.7990          NA        NA        NA
##   VAL =~ val2        0.8374          NA        NA        NA
##   VAL =~ val3        0.6934          NA        NA        NA
##   VAL =~ val4        0.7247          NA        NA        NA
##   SAT =~ sat1        0.8996          NA        NA        NA
##   SAT =~ sat2        0.9048          NA        NA        NA
##   SAT =~ sat3        0.7715          NA        NA        NA
##   SAT =~ sat4        0.7462          NA        NA        NA
##   LOY =~ loy1        0.8532          NA        NA        NA
##   LOY =~ loy2        0.6211          NA        NA        NA
##   LOY =~ loy3        0.8294          NA        NA        NA
##   LOY =~ loy4        0.6554          NA        NA        NA
## ______________________________________________________________________________________________________________</code></pre>
<p>Finally, the <em>‘verify’</em>-function checks whether the calculated results are admissible. That is to say, it is verified that all results are consonant with the theory underlying the estimation. If the results based on an estimated model exhibit one of the following defects they are deemed inadmissible: - non-convergence - loadings and/or reliabilities larger than 1 - a construct VCV and/or a model-implied VCV matrix that is not positive (semi-)definite</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1"><span class="kw"><a href="../reference/verify.html">verify</a></span>(results1)</a></code></pre></div>
<pre><code>## ______________________________________________________________________________________________________________
## 
## Verify admissibility:
## 
##   admissible
## 
## Details:
## 
##   Code   Status    Description
##   1      ok        Convergence                                   
##   2      ok        At least one standardized loadings &gt; 1        
##   3      ok        Construct VCV not positive semi-definite      
##   4      ok        Model-implied VCV not positive semi-definite  
##   5      ok        At least one proxy reliability &gt; 1            
## ______________________________________________________________________________________________________________</code></pre>
<p>The output shows that the estimation results of the example are admissible, every status is set to “ok”.</p>
<p>Having carried out the estimation of all parameters and having established that they are all admissible, it is now question to interpret the results. The influence of (exogenous) constructs on (endogenous) constructs is described by the structural model and expressed by the estimated path coefficients (reliabilities):</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1">results1<span class="op">$</span>Estimates<span class="op">$</span>Path_estimates</a></code></pre></div>
<pre><code>##           IMAG        EXPE       QUAL       VAL       SAT LOY
## IMAG 0.0000000  0.00000000 0.00000000 0.0000000 0.0000000   0
## EXPE 0.6087192  0.00000000 0.00000000 0.0000000 0.0000000   0
## QUAL 0.0000000  0.93972855 0.00000000 0.0000000 0.0000000   0
## VAL  0.0000000 -0.21464046 1.03645684 0.0000000 0.0000000   0
## SAT  0.0869362 -0.02526299 0.03786809 0.8274078 0.0000000   0
## LOY  0.3119949  0.00000000 0.00000000 0.0000000 0.5097847   0</code></pre>
<p>The way estimated loadings and weights are provided is the same: The user is always given a matrix which consists of the variables involved in the respective submodel of GSCA<sub>M</sub> (resp. GSCA). For the path estimates, the columns of the output matrix stand for the constructs that exert an influence and the rows for those constructs that are influenced.</p>
<p>For example, in the considered dataset the user gets for the path coefficient “IMAG” on “EXPE” an estimated value of:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1">results1<span class="op">$</span>Estimates<span class="op">$</span>Path_estimates[<span class="st">"EXPE"</span>,<span class="st">"IMAG"</span>]</a></code></pre></div>
<pre><code>## [1] 0.6087192</code></pre>
<p>This value describes the influence of the construct “Consumer’s image of the enterprise” on the construct “Consumer’s expectation”. As data are standardized, also parameter estimates are standardized. Therefore, they measure the change of a variable in standard deviations. This has to be taken into account when interpreting the results. Thus, an increase of “IMAG” by one standard deviation leads to an increase of “EXPE” by 0.6087192 standard deviations. If the original units of the data are known, the estimated parameters can be transformed in these units to make a more meaningful interpretation possible. Furthermore, path coefficients can be seen as the reliabilities of the constructs. Thus, the path coefficient in the example stands for the portion of the total variance of the construct “EXPE” which is explained by the construct “IMAG”.</p>
<p>Next, the loadings are to be interpreted. The loading is the correlation between a construct (resp. its proxy) and an indicator. Obviously, this correlation always exists and can always be calculated. To this end, it is important to point out that in the scope of the <em>cSEM</em>-package two types of loadings are distinguished. The type of a specific loading is strongly related to the type of the construct which is connected by the loading to an indicator. On the one side, there are pure composite constructs. These constructs are an exact linear combination of their indicators and do not influence their indicators. Therefore, the constructs can be calculated exactly when weights have been estimated. In this case, the loading is the correlation between the “true” construct and its indicator (“composite loading”). On the other side, there are common factor constructs. For these constructs, only proxy values can be calculated using the estimated weights. Thus, the loading represents in this case the correlation between indicator and proxy and not between indicator and true underlying but unknown construct (“construct loading”).</p>
<p>When estimating coefficients with GSCA, Hwang and Takane state that loadings are set equal to zero for all composite type constructs because these constructs do not exert any influence on their related indicators. This means in the language of the <em>cSEM</em>-package that the “construct loading” does not need to be calculated with the chosen estimation method since it is not of any further interest. The reason is that these constructs are the exact linear combination of their indicators and, therefore, the “true” correlation (which is of interest) can be calculated directly without proxies as an intermediate step. Also in this case, this correlation exists and is part of the resulting estimation output of the <em>csem</em>-function when composite type constructs are under consideration.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1">results1<span class="op">$</span>Estimates<span class="op">$</span>Loading_estimates[<span class="st">"EXPE"</span>, <span class="st">"expe1"</span>]</a></code></pre></div>
<pre><code>## [1] 0.7597724</code></pre>
<p>This result shows, that the correlation between the proxy of the construct “EXPE” and its first indicator “expe1” is 0.7597724.</p>
<p>Finally, squared loadings and squared path coefficients are squared multiple correlations of the variables connected by the related unsquared parameters.</p>
<p>Altogether, these interpretations and relationships also offer a way to assess the reliability of the indicators and to analyze whether the model is well specified or not. Loadings (as well as path coefficients) should be statistically significantly different from zero. Otherwise they could be omitted from the model. Moreover, it is recommended that the absolute value of each loading (“composite” as well as “construct”) is greater than 0.7 <span class="citation">(see Hwang and Takane 2014, 31)</span>.</p>
</div>
<div id="example2" class="section level3">
<h3 class="hasAnchor">
<a href="#example2" class="anchor"></a>Example 2: Pure common factor model and GSCA</h3>
<p>In the next example, the same model as in <a href="#example1">Example1</a> is considered. However, estimation is now done with GSCA. As already mentioned, this can be achieved by setting the argument <em>‘.disattenuate’</em> equal to <em>FALSE</em>. In this case, estimators can be biased when constructs are of common factor type and no pure composites.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1">results2 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/csem.html">csem</a></span>(satisfaction, model, <span class="dt">.approach_weights =</span> <span class="st">"GSCA"</span>, <span class="dt">.disattenuate =</span> <span class="st">"FALSE"</span>)</a></code></pre></div>
<p>For the path coefficient and the loading already considered in <a href="#example1">Example1</a>, the estimated values are now:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1">results2<span class="op">$</span>Estimates<span class="op">$</span>Path_estimates[<span class="st">"EXPE"</span>,<span class="st">"IMAG"</span>]</a></code></pre></div>
<pre><code>## [1] 0.5565924</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1">results2<span class="op">$</span>Estimates<span class="op">$</span>Loading_estimates[<span class="st">"EXPE"</span>, <span class="st">"expe1"</span>]</a></code></pre></div>
<pre><code>## [1] 0.7773295</code></pre>
<p>The interpretation of the estimators is the same as in the case of GSCA<sub>M</sub> (see <a href="#example1">Example1</a>). However, by comparing these values with those calculated before, the bias in (some) estimators when using GSCA becomes obvious. Thus, when interpreting these values the user should keep in mind that the estimators might be biased.</p>
</div>
<div id="example3" class="section level3">
<h3 class="hasAnchor">
<a href="#example3" class="anchor"></a>Example 3: At least one composite and GSCA<sub>M</sub>
</h3>
<p>Now, the specified model will be modified. The aim is to consider models with at least one construct of composite type. <a href="#example1">Example 1</a> and <a href="#example2">Example 2</a> show that in the case of a pure common factor model, estimation can be carried out either with GSCA or with GSCA<sub>M</sub>. We use the same dataset as before, but the constructs “EXPE”, “IMAG”, “SAT” and “VAL” are now of composite type. This means that, these constructs are interpreted such that they do not have an influence on their respective indicators. Thus, they are only modeled as an (exact) linear combination (composite) of their indicators. For these constructs, construct loadings do not need to be calculated. The structural model stays the same.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1">model2 &lt;-<span class="st"> "</span></a>
<a class="sourceLine" id="cb23-2" data-line-number="2"><span class="st"># Structural model</span></a>
<a class="sourceLine" id="cb23-3" data-line-number="3"><span class="st">QUAL ~ EXPE</span></a>
<a class="sourceLine" id="cb23-4" data-line-number="4"><span class="st">EXPE ~ IMAG</span></a>
<a class="sourceLine" id="cb23-5" data-line-number="5"><span class="st">SAT  ~ IMAG + EXPE + QUAL + VAL</span></a>
<a class="sourceLine" id="cb23-6" data-line-number="6"><span class="st">LOY  ~ IMAG + SAT</span></a>
<a class="sourceLine" id="cb23-7" data-line-number="7"><span class="st">VAL  ~ EXPE + QUAL</span></a>
<a class="sourceLine" id="cb23-8" data-line-number="8"></a>
<a class="sourceLine" id="cb23-9" data-line-number="9"><span class="st"># Measurement model (common factors and composites)</span></a>
<a class="sourceLine" id="cb23-10" data-line-number="10"></a>
<a class="sourceLine" id="cb23-11" data-line-number="11"><span class="st">EXPE &lt;~ expe1 + expe2 + expe3 + expe4 + expe5</span></a>
<a class="sourceLine" id="cb23-12" data-line-number="12"><span class="st">IMAG &lt;~ imag1 + imag2 + imag3 + imag4 + imag5</span></a>
<a class="sourceLine" id="cb23-13" data-line-number="13"><span class="st">LOY  =~ loy1  + loy2  + loy3  + loy4</span></a>
<a class="sourceLine" id="cb23-14" data-line-number="14"><span class="st">QUAL =~ qual1 + qual2 + qual3 + qual4 + qual5</span></a>
<a class="sourceLine" id="cb23-15" data-line-number="15"><span class="st">SAT  &lt;~ sat1  + sat2  + sat3  + sat4</span></a>
<a class="sourceLine" id="cb23-16" data-line-number="16"><span class="st">VAL  &lt;~ val1  + val2  + val3  + val4</span></a>
<a class="sourceLine" id="cb23-17" data-line-number="17"><span class="st">"</span></a></code></pre></div>
<p>Calling the <em>csem</em>-function in this case without setting the argument <em>‘.disattenuate’</em> equal to <em>FALSE</em> will produce the error already mentioned in the <a href="#introduction">Introduction</a>. For a model like the specified one, i.e. with at least one construct of composite type, estimation cannot be done with GSCA<sub>M</sub>:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1"><span class="kw"><a href="../reference/csem.html">csem</a></span>(satisfaction, model2, <span class="dt">.approach_weights =</span> <span class="st">"GSCA"</span>, <span class="dt">.disattenuate =</span> <span class="st">"TRUE"</span>)</a></code></pre></div>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1">Error<span class="op">:</span><span class="st"> </span>The following error occured <span class="cf">in</span> the <span class="st">`</span><span class="dt">calculateWeightsGSCAm()</span><span class="st">`</span> <span class="cf">function</span><span class="op">:</span></a>
<a class="sourceLine" id="cb25-2" data-line-number="2">GSCAm only applicable to pure common factor models. Use <span class="st">`</span><span class="dt">.disattenuate = FALSE</span><span class="st">`</span>. </a></code></pre></div>
<p>Since GSCA<sub>M</sub> is not an option for those models, parameter estimates have to be determined using “standard” GSCA (see <a href="#example4">Example 4</a>).</p>
</div>
<div id="example4" class="section level3">
<h3 class="hasAnchor">
<a href="#example4" class="anchor"></a>Example 4: At least one composite and GSCA</h3>
<p>In the last example, the same model as before is considered: common factor type constructs are combined with composite type constructs. However, estimation is now done with “standard” GSCA, i.e., <em>‘.disattenuate’</em> is explicitly set to <em>FALSE</em>. Therefore, calling the <em>csem</em>-function with these input arguments does not produce an error.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1">results4 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/csem.html">csem</a></span>(satisfaction, model2, <span class="dt">.approach_weights =</span> <span class="st">"GSCA"</span>, <span class="dt">.disattenuate =</span> <span class="st">"FALSE"</span>)</a></code></pre></div>
<p>This leads to the following estimation results:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1"><span class="kw"><a href="../reference/summarize.html">summarize</a></span>(results4)</a></code></pre></div>
<pre><code>## ______________________________________________________________________________________________________________
## -------------------------------------------------- Overview --------------------------------------------------
## 
##  Number of observations           = 250
##  Weight estimator                 = GSCA
##  Type of indicator correlation    = Bravais-Pearson
##  Path model estimator             = OLS
##  Type of path model               = Linear
##  Disattenuated                    = no
## 
##  Construct details:
##  ------------------
##  Name  Modeled as     Order         
## 
##  IMAG  Composite      First order   
##  EXPE  Composite      First order   
##  QUAL  Common factor  First order   
##  VAL   Composite      First order   
##  SAT   Composite      First order   
##  LOY   Common factor  First order   
## 
## -------------------------------------------------- Estimates -------------------------------------------------
## 
## Estimated path coefficients:
## ============================
##   Path           Estimate  Std. error   t-stat.   p-value
##   EXPE ~ IMAG      0.6139          NA        NA        NA
##   QUAL ~ EXPE      0.8487          NA        NA        NA
##   VAL ~ EXPE       0.1605          NA        NA        NA
##   VAL ~ QUAL       0.6409          NA        NA        NA
##   SAT ~ IMAG       0.1910          NA        NA        NA
##   SAT ~ EXPE       0.0004          NA        NA        NA
##   SAT ~ QUAL       0.0776          NA        NA        NA
##   SAT ~ VAL        0.6442          NA        NA        NA
##   LOY ~ IMAG       0.2438          NA        NA        NA
##   LOY ~ SAT        0.5298          NA        NA        NA
## 
## Estimated Loadings:
## ===================
##   Loading          Estimate  Std. error   t-stat.   p-value
##   IMAG =~ imag1      0.5561          NA        NA        NA
##   IMAG =~ imag2      0.8320          NA        NA        NA
##   IMAG =~ imag3      0.8319          NA        NA        NA
##   IMAG =~ imag4      0.4752          NA        NA        NA
##   IMAG =~ imag5      0.8503          NA        NA        NA
##   EXPE =~ expe1      0.7113          NA        NA        NA
##   EXPE =~ expe2      0.8727          NA        NA        NA
##   EXPE =~ expe3      0.7046          NA        NA        NA
##   EXPE =~ expe4      0.7830          NA        NA        NA
##   EXPE =~ expe5      0.8088          NA        NA        NA
##   QUAL =~ qual1      0.7789          NA        NA        NA
##   QUAL =~ qual2      0.8792          NA        NA        NA
##   QUAL =~ qual3      0.7509          NA        NA        NA
##   QUAL =~ qual4      0.8294          NA        NA        NA
##   QUAL =~ qual5      0.8189          NA        NA        NA
##   VAL =~ val1        0.9138          NA        NA        NA
##   VAL =~ val2        0.7657          NA        NA        NA
##   VAL =~ val3        0.6586          NA        NA        NA
##   VAL =~ val4        0.8495          NA        NA        NA
##   SAT =~ sat1        0.9607          NA        NA        NA
##   SAT =~ sat2        0.9208          NA        NA        NA
##   SAT =~ sat3        0.7382          NA        NA        NA
##   SAT =~ sat4        0.7835          NA        NA        NA
##   LOY =~ loy1        0.9102          NA        NA        NA
##   LOY =~ loy2        0.6857          NA        NA        NA
##   LOY =~ loy3        0.9086          NA        NA        NA
##   LOY =~ loy4        0.6434          NA        NA        NA
## 
## Estimated Weights:
## ==================
## 
##   Weights          Estimate  Std. error   t-stat.   p-value
##   IMAG &lt;~ imag1     -0.0360          NA        NA        NA
##   IMAG &lt;~ imag2      0.2769          NA        NA        NA
##   IMAG &lt;~ imag3      0.3585          NA        NA        NA
##   IMAG &lt;~ imag4      0.0618          NA        NA        NA
##   IMAG &lt;~ imag5      0.5434          NA        NA        NA
##   EXPE &lt;~ expe1      0.0851          NA        NA        NA
##   EXPE &lt;~ expe2      0.4180          NA        NA        NA
##   EXPE &lt;~ expe3      0.1759          NA        NA        NA
##   EXPE &lt;~ expe4      0.3162          NA        NA        NA
##   EXPE &lt;~ expe5      0.2512          NA        NA        NA
##   VAL &lt;~ val1        0.4999          NA        NA        NA
##   VAL &lt;~ val2        0.1841          NA        NA        NA
##   VAL &lt;~ val3        0.1218          NA        NA        NA
##   VAL &lt;~ val4        0.3790          NA        NA        NA
##   SAT &lt;~ sat1        0.5274          NA        NA        NA
##   SAT &lt;~ sat2        0.3398          NA        NA        NA
##   SAT &lt;~ sat3        0.0341          NA        NA        NA
##   SAT &lt;~ sat4        0.1983          NA        NA        NA
## ______________________________________________________________________________________________________________</code></pre>
<p>Due to the fact that there are some constructs that are of composite type, estimation must happen with GSCA. This might result in biased estimators (as in <a href="#example2">Example2</a> for the model where all constructs are of common factor type). However, the interpretation of estimated coefficients is done in the same way as outlined in <a href="#example1">Example1</a> keeping in mind that estimators might be biased. Note that the estimated (“composite”) loadings represent in this case the “true” correlations between indicators and constructs (not proxies!) for all composite type constructs.</p>
</div>
</div>
<div id="methods" class="section level1">
<h1 class="hasAnchor">
<a href="#methods" class="anchor"></a>Methods &amp; Formula</h1>
<div id="the-gsca-gscam-model" class="section level3">
<h3 class="hasAnchor">
<a href="#the-gsca-gscam-model" class="anchor"></a>The GSCA-/GSCA<sub>M</sub>-model</h3>
<p>This section is based on <span class="citation">(Hwang, Takane, and Jung 2017, 1–4)</span> and <span class="citation">(Hwang and Takane 2014, chap. 2.1.-2.2)</span> where the GSCA-/GSCA<sub>M</sub>-model and the parameter estimation are outlined.</p>
<p>As already mentioned in the introduction, GSCA and GSCA<sub>M</sub> are composite-based approaches to estimation of parameters in structural equation models.</p>
<p>The estimation within GSCA (resp. GSCA<sub>M</sub>) begins with the standardization of the data and the specification of three submodels. The matrix of the standardized data is denoted by <span class="math inline">\(\mathbf{X}\)</span> and is of dimension <em>N</em> <em>x</em> <em>K</em> since there are <em>N</em> observations in <em>K</em> indicators. Additionally, there are <em>J</em> constructs (latent variables).</p>
<p>As in PLS, the measurement model and the structural model are defined to specifiy the relations of latent variables on indicators resp. of the exogenous latent variables on the endogenous ones. In addition, the weighted relation model accounts for the influence of the indicators on the latent variables. Each submodel is expressed in a matrix equation leading to the following 3 equations:</p>
<ol style="list-style-type: decimal">
<li><p>Matrix equation of the measurement model: <span class="math display">\[ \mathbf{X} = \boldsymbol{\Gamma}  \boldsymbol{\Lambda} + \mathbf{U} \mathbf{D} + \mathbf{E_{1}} \]</span> In the measurement model, relationships between indicators and constructs are specified. The matrix <span class="math inline">\(\boldsymbol{\Gamma}\)</span> is the <em>N</em> by <em>J</em> matrix which contains columnwise the constructs <span class="math inline">\(\gamma_{1}\)</span> up to <span class="math inline">\(\gamma_{J}\)</span>. The matrix <span class="math inline">\(\boldsymbol{\Lambda}\)</span> is the <em>J</em> by <em>K</em> matrix of (“construct”) loadings relating constructs and indicators. <span class="math inline">\(\mathbf{U}\)</span> denotes the <em>N</em> by <em>K</em> matrix of unique variables and <span class="math inline">\(\mathbf{D}\)</span> is the <em>K</em> by <em>K</em> diagonal matrix of unique loadings. Therefore, the matrix <span class="math inline">\(\boldsymbol{\Gamma} \boldsymbol{\Lambda}\)</span> represents the common parts of the indicators whereas <span class="math inline">\(\mathbf{U} \mathbf{D}\)</span> stands for the unique parts. Finally, <span class="math inline">\(\mathbf{E_{1}}\)</span> is the <em>N</em> by <em>K</em> matrix containing the residuals of indicators. It is assumed that <span class="math inline">\(\boldsymbol{\Gamma}\)</span> is uncorrelated with <span class="math inline">\(\mathbf{U}\)</span>, i.e. <span class="math inline">\(\boldsymbol{\Gamma}' \mathbf{U}\)</span> = <span class="math inline">\(\mathbf{U}' \boldsymbol{\Gamma} = \mathbf{0}\)</span>, and that <span class="math inline">\(\mathbf{U}\)</span> is orthonormalized.</p></li>
<li><p>Matrix equation of the structural model:</p></li>
</ol>
<p><span class="math display">\[ \boldsymbol{\Gamma} = \boldsymbol{\Gamma}  \mathbf{B'} + \mathbf{E_{2}} \]</span> In the structural model, relationships between constructs are specified. The matrix <span class="math inline">\(\boldsymbol{\Gamma}\)</span> is defined as in the measurement model, the matrix <span class="math inline">\(\mathbf{B}\)</span> is the <em>J</em> <em>x</em> <em>J</em> matrix of path coefficients and <span class="math inline">\(\mathbf{E_{2}}\)</span> is the <em>N</em> by <em>J</em> matrix of the residuals for the constructs.</p>
<ol start="3" style="list-style-type: decimal">
<li>Matrix equation of the weighted relation model:</li>
</ol>
<p><span class="math display">\[ \boldsymbol{\Gamma} = ( \mathbf{X} - \mathbf{U} \mathbf{D}) \mathbf{W'} \]</span> In the weighted relation model, constructs (in the matrix <span class="math inline">\(\boldsymbol{\Gamma}\)</span>) are expressed as an exact linear combination (composite) of the corresponding indicators (matrix <span class="math inline">\(\mathbf{X}\)</span>) with their unique parts (matrix <span class="math inline">\(\mathbf{UD}\)</span>) removed. The <em>J</em> by <em>K</em> matrix <span class="math inline">\(\mathbf{W}\)</span> contains the weights of the indicators in the linear combinations.</p>
<p>Note that the authors in <span class="citation">Hwang and Takane (2004)</span>, <span class="citation">Hwang et al. (2010)</span>, <span class="citation">Hwang and Takane (2014)</span> and <span class="citation">Hwang, Takane, and Jung (2017)</span> use a completely different notation compared to the standard LISREL/Bollen-type notation. For example, the total number of indicators is there denoted by <em>J</em> and the total number of constructs by <em>P</em>. Moreover, the matrix of indicator values, i.e. the data matrix, is called <strong>Z</strong> in the literature. The implementation of GSCA and GSCA<sub>m</sub> in the <em>cSEM</em>-package uses the LISREL notation.</p>
<p>Setting the matrix <span class="math inline">\(\mathbf{U}\)</span> equal to the zero matrix of the corresponding dimension leads to the equations of the three GSCA submodels. Thus, the difference of both approaches is that in GSCA indicators do not have a unique part and are only modeled by their constructs and some error terms. However, including the unique term makes it possible to account for errors in observations of indicators which leads to unbiased paramater estimators. That is why, GSCA<sub>m</sub> is the consistent alternative to GSCA.</p>
<p>In the next step, the three submodels are combined to the GSCA (resp. GSCA<sub>M</sub>)-model expressed by one (unified) model equation:</p>
<p><span class="math display">\[ [\mathbf{Z}, \boldsymbol{\Gamma}] =  \boldsymbol{\Gamma} [\boldsymbol{\Lambda}', \mathbf{B}'] + [\mathbf{UD},\mathbf{0}] + [\mathbf{E_{1}}, \mathbf{E_{2}}] \]</span> In short notation, this equation becomes by renaming: <span class="math display">\[ \boldsymbol{\Psi} = \boldsymbol{\Gamma} \mathbf{A} + \mathbf{S} + \mathbf{E} \]</span> This is the GSCA<sub>M</sub>-model. Since <span class="math inline">\(\mathbf{S} = \mathbf{0}\)</span>, iff <span class="math inline">\(\mathbf{U} = \mathbf{0}\)</span> the GSCA-model is:</p>
<p><span class="math display">\[ \boldsymbol{\Psi} = \boldsymbol{\Gamma} \mathbf{A} + \mathbf{E} \]</span></p>
</div>
<div id="parameter-estimation" class="section level3">
<h3 class="hasAnchor">
<a href="#parameter-estimation" class="anchor"></a>Parameter estimation</h3>
<p>Parameter estimation within GSCA or GSCA<sub>M</sub> is based on minimizing a global optimization criterion <span class="math inline">\(\phi\)</span> via least squares. This optimization criterion is a direct consequence of the model equation:</p>
<p><span class="math display">\[ \phi = \text{SS}(\mathbf{E}) = \text{SS}(\boldsymbol{\Psi} - \boldsymbol{\Gamma} \mathbf{A} - \mathbf{S}) \]</span> In this equation <span class="math inline">\("\text{SS}"\)</span> stands for the sum of squares of the related matrix. For any matrix <span class="math inline">\(X\)</span>, it holds: <span class="math display">\[\text{SS}(X) = \text{trace}(X'X)\]</span></p>
<p>The minimization happens under the constraint that <span class="math inline">\(\gamma_{j}' \gamma_{j} = 1\)</span> <span class="math inline">\((j=1,...,J)\)</span>, <span class="math inline">\(\mathbf{U}' \boldsymbol{\Gamma} = \mathbf{0}\)</span> and <span class="math inline">\(\mathbf{U}' \mathbf{U} = \boldsymbol{I_{J}}\)</span> where <span class="math inline">\(\boldsymbol{I_{J}}\)</span> is the identity matrix of dimension <em>J</em> (see <span class="citation">Hwang, Takane, and Jung (2017)</span>, p.3). Minimization of <span class="math inline">\(\phi\)</span> is done via an iterative algorithm: the Alternating Least Squares Algorithm. To this end, the whole set of parameters is divided into subsets (<span class="math inline">\(\boldsymbol{\Gamma}, \mathbf{A}, \mathbf{U}, \mathbf{D}\)</span> for GSCA<sub>M</sub>).</p>
<p>The ALS algorithm now iteratively updates one of these sets of parameters in a least squares sense while keeping all other parameters fixed. In every step, this updating consists essentially in regressions of some variables on the others. By this, optimal parameter estimates are calculated and the value of the optimization criterion <span class="math inline">\(\phi\)</span> decreases. This step is repeated (alternating in every step the set of parameters which is updated) until convergence is reached. Convergence means that the decrease of <span class="math inline">\(\phi\)</span> falls below an (initially defined) threshold <em>‘.tolerance’</em> (default value: <span class="math inline">\(10^{-5}\)</span>) or that the maximum number of iterations <em>‘.iter_max’</em> (default value: 100) was carried out. In fact, the latter means that the algorithm did not converge and the latest estimators were returned. Both arguments, <em>‘.tolerance’</em> as well as <em>‘.iter_max’</em>, can be set to any other value by the user when calling the <em>csem()</em>-function.</p>
<p>For more information about the theoretical background of parameter estimation in GSCA (or GSCA<sub>M</sub>) in general and especially the Alternating Least Squares Algorithm see for example <span class="citation">Hwang and Takane (2004)</span> and <span class="citation">Hwang, Takane, and Jung (2017)</span>.</p>
</div>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<div id="refs" class="references">
<div id="ref-Hwang2010">
<p>Hwang, Heungsun, Naresh K. Malhotra, Youngchan Kim, Marc A. Tomiuk, and Sungjin Hong. 2010. “A Comparative Study on Parameter Recovery of Three Approaches to Structural Equation Modeling.” <em>Journal of Marketing Research</em> 47 (4). American Marketing Association: 699–712.</p>
</div>
<div id="ref-Hwang2004">
<p>Hwang, Heungsun, and Yoshio Takane. 2004. “Generalized Structured Component Analysis.” <em>Psychometrika</em> 69 (1). Springer: 81–99.</p>
</div>
<div id="ref-Hwang2014">
<p>———. 2014. <em>Generalized Structured Component Analysis: A Component-Based Approach to Structural Equation Modeling</em>. Chapman <span class="math inline">\(\&amp;\)</span> Hall/Crc Statistics in the Social and Behavioral Sciences. Chapman; Hall/CRC.</p>
</div>
<div id="ref-Hwang2017">
<p>Hwang, Heungsun, Yoshio Takane, and Kwanghee Jung. 2017. “Generalized Structured Component Analysis with Uniqueness Terms for Accommodating Measurement Error.” <em>Frontiers in Psychology</em> 8 (2137). Frontiers Media: 1–12.</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#introduction">Introduction</a></li>
      <li><a href="#usage">Syntax and Options</a></li>
      <li><a href="#examples">Usage &amp; Examples</a></li>
      <li><a href="#methods">Methods &amp; Formula</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Manuel Rademaker, Florian Schuberth.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.9000.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
