# # --- Internal helpers (same file, not exported) ------------------------------
# 
# # --- Internal state (no globals leaked) --------------------------------------
# .pkg_state <- new.env(parent = emptyenv())
# .pkg_state$best_individuals_all <- list()
# .pkg_state$best_individual      <- NULL
# .pkg_state$best_fitness         <- -Inf




#' Do a model specification search
#'
#' \lifecycle{"experimental"}
#'
#' Perform a model search \insertCite{Hair2016;textual}{cSEM}
#'
#' @usage dfunction(.object = NULL, 
#' .n_exogenous = 3,
#' .popsize = 20,
#' .maxiter=20,
#' .mutation_prob = 0.5,
#' .seeds = c(2, 4, 5),
#' .only_structural = FALSE)
#'
#' @return The mean matrix generated by the AGAS-PLS runs
#' 
#' @inheritParams csem_arguments
#' 
#' @seealso [cSEMResults]
#' 
#' @references \insertAllCited{}
#' 
#' @export
doModelSearch <- function(.object = NULL, 
                          .n_exogenous = 3,
                          .popsize = 20, 
                          .maxiter=20,
                          .mutation_prob = 0.5,
                          .seeds = c(2, 4, 5), 
                          .only_structural = FALSE){
  
  if(inherits(.object, "cSEMResults_multi")) {
    out <- lapply(.object, doModelSearch, 
                  .n_exogenous = .n_exogenous,
                  .popsize = .popsize,
                  .maxiter = .maxiter,
                  .mutation_prob = .mutation_prob, 
                  .seeds = .seeds, 
                  .only_structural = .only_structural)
    return(out)
    
  } else if(inherits(.object, "cSEMResults_default")) {
    
    # Do some preliminary checks
    
    if(.object$Information$Model$model_type != 'Linear'){
      stop2('Currently, `doModelSearch()` supports only linear models.')
    }
    
    if(.object$Information$Arguments$.approach_weights != "PLS-PM"){
      stop2("Currently, `doModelSearch()` supports only PLS-PM.")
    }
    
    if (!requireNamespace("GA", quietly = TRUE)) {
      stop2(
        "Package `GA` required. Use `install.packages(\"GA\")` and rerun.")
    }
    
    
    # Retrieve information on the model (number variables, name variables)
    # path_estimates <- .object$Estimates$Path_estimates 
    
    .variables <- rownames(.object$Information$Model$measurement)
    .n_variables <- length(.variables)
    .measurement_model <- lapply(seq(1,nrow(.object$Information$Model$measurement)),
                                 function(x){colnames(.object$Information$Model$measurement)[.object$Information$Model$measurement[x,]==1]})
    names(.measurement_model) <- rownames(.object$Information$Model$measurement)
    # .measurement_model <- transform_measurement_model(.object$Information$Model$measurement)
    
    
    # TODO: ALLOW FOR MORE MS CRITERIA
    # compute criteria once
    model_criteria <- calculateModelSelectionCriteria(
      .object,
      .by_equation = FALSE,
      .only_structural = .only_structural,
      .ms_criterion = 'bic'
    )
    
    BIC = model_criteria$BIC
    # print(BIC)
    
    .agas_dataset <- .object$Information$Data
    
    seeds <- as.integer(.seeds)
    mat_list <- vector("list", length(.seeds))
    names(mat_list) <- as.character(.seeds)
    
    for (i in seq_along(.seeds)) {
      
      .pkg_state$best_individuals_all <- list()
      .pkg_state$best_individual      <- NULL
      .pkg_state$best_fitness         <- -Inf
      
      ga_control <- GA::ga(
        type = "binary",
        nBits = .n_variables * .n_variables,
        popSize = .popsize,
        maxiter = .maxiter,
        pmutation = 1.0,
        pcrossover = 0.8,
        fitness = function(x) .agas_fitness(x, .agas_dataset, .n_exogenous, .measurement_model, .variables, .only_structural),
        elitism = TRUE,
        parallel = FALSE,
        seed = i,
        mutation = function(object, parent) .agas_mutation(object, parent, .n_variables, .mutation_prob, .n_exogenous)
      )
      mat_list[[i]] <- .pkg_state$best_individual
    }
    
    arr <- array(unlist(mat_list),
                 dim = c(.n_variables, .n_variables, length(mat_list)))
    mean_mat <- apply(arr, c(1, 2), mean, na.rm = TRUE)
    rownames(mean_mat) <- .variables
    colnames(mean_mat) <- .variables
    
    print(mean_mat)
    out <- .matrix_to_string(mean_mat)
    return(out)
    
    
    
    
  }else if(inherits(.object, "cSEMResults_2ndorder")) {
    stop2("Currently, `doModelSearch()` is not implemented for models", 
          " containing second-order constructs.")
  } else {
    stop2("`.object` must be of class cSEMResults")
  }
}
