# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arma_svd_X <- function(X, y) {
    .Call(`_cSEM_arma_svd_X`, X, y)
}

arma_svd_XtX <- function(X, y) {
    .Call(`_cSEM_arma_svd_XtX`, X, y)
}

arma_pinv <- function(X, y) {
    .Call(`_cSEM_arma_pinv`, X, y)
}

arma_solve <- function(X, y) {
    .Call(`_cSEM_arma_solve`, X, y)
}

arma_update_U_qrQ <- function(Eta_normed, Z_normed, D) {
    .Call(`_cSEM_arma_update_U_qrQ`, Eta_normed, Z_normed, D)
}

arma_update_U_qrqty <- function(Eta_normed, Z_normed, D) {
    .Call(`_cSEM_arma_update_U_qrqty`, Eta_normed, Z_normed, D)
}

