# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kroneckerC <- function(X, Y, idx) {
    .Call(`_cSEM_kroneckerC`, X, Y, idx)
}

kroneckerCsp <- function(X, Y, idx) {
    .Call(`_cSEM_kroneckerCsp`, X, Y, idx)
}

